//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_DatPhong
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tb_DatPhong()
        {
            this.tb_DatPhong_CT = new HashSet<tb_DatPhong_CT>();
        }
    
        public int IDDP { get; set; }
        public int IDKH { get; set; }
        public int IDPHONG { get; set; }
        public Nullable<System.DateTime> NGAYDAT { get; set; }
        public Nullable<System.DateTime> NGAYTRA { get; set; }
        public Nullable<double> SOTIEN { get; set; }
        public Nullable<int> SONGUOIO { get; set; }
        public int ID_USER { get; set; }
        public int IDSP { get; set; }
        public string MAKS { get; set; }
        public string MADVI { get; set; }
        public Nullable<bool> STATUS { get; set; }
        public Nullable<bool> THEODOAN { get; set; }
        public string GHICHU { get; set; }
        public Nullable<System.DateTime> CREATED_DATE { get; set; }
        public Nullable<System.DateTime> UPDATE_DATE { get; set; }
        public Nullable<System.DateTime> UPDATE_BY { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tb_DatPhong_CT> tb_DatPhong_CT { get; set; }
        public virtual tb_DonVi tb_DonVi { get; set; }
        public virtual tb_KhachHang tb_KhachHang { get; set; }
        public virtual tb_KhachSan tb_KhachSan { get; set; }
        public virtual tb_SanPham tb_SanPham { get; set; }
        public virtual tb_Users tb_Users { get; set; }
        public virtual tb_Phong tb_Phong { get; set; }
    }
}
